name: Run Synthesis
on:
  workflow_dispatch:
  push:
    branches: [ trunk ]

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/base-band/docker-images/quartus-ci-build:latest
      options: --net=host
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          QPATH=/root/intelFPGA_lite/20.1/quartus make
        name: Run in container