name: Run Synthesis
on:
  workflow_dispatch:
  push:
    branches: [ trunk ]

jobs:
  run-synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: free -h
      - run: df -h
      - run: docker run -dit --name qrt --net=host -v $(pwd):/src ghcr.io/base-band/docker-images/quartus-ci-build:latest
      - run: docker exec qrt bash -c 'make -C /src'
      - run: free -h
      - run: df -h
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: bitfile
          path: output_files