name: Run Synthesis
on:
  workflow_dispatch:
  push:
    branches: [ ben/ci1 ]

jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: pwd
      - run: whoami
      - run: free -h
      - run: df -h