name: Run Synthesis
on:
  workflow_dispatch:
  push:
    branches: [ ben/ci1 ]

jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: pwd
      - run: whoami
      - run: free -h
      - run: df -h
      - run: which docker
      - run: docker run -dit --name qrt --net=host -v $(pwd):/src ubuntu:18.04
      - run: docker exec qrt apt update
      - run: docker exec qrt apt install -y iproute2
      - run: docker exec qrt ip a
      - run: docker exec qrt whoami