name: Run Synthesis
on:
  workflow_dispatch:
  push:
    branches: [ trunk ]

jobs:
  test_stuff:
    runs-on: ubuntu-latest  
    - run: |
        ls
        whoami
        pwd
        free -h
        df -h
      name: Run in container