name: Run Synthesis
on:
  workflow_dispatch:
  push:
    branches: [ trunk ]

# This flow does not use the "container" option. This is required due to
# a segfault produced by quartus if there is a virtual NIC. The solution
# is to pass --net=host however this doesn't work with github's builtin
# "container". We are forced to run docker explicitly, and use
# "docker exec" to run things inside

jobs:
  run-synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: free -h
      - run: df -h
      - run: docker run -dit --name qrt --net=host -v $(pwd):/src ghcr.io/base-band/docker-images/quartus-ci-build:latest
      - run: docker exec qrt bash -c 'make -C /src'
      - run: free -h
      - run: df -h
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: bitfile
          path: output_files